title:       "Weight-Space Symmetries:<br> from Foundations to Practical Applications"
description: "Workshop held in conjunction with the International Conference on Machine Learning (ICML) 2026 in Seoul, South Korea."

timezone: Asia/Seoul

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  # Schedule: "/schedule"
  Speakers: "/speakers"
  Organizers: "/organizers"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
