title:       "ICML 2026 Workshop on Weight-Space Symmetries: from Foundations to Practical Applications"
description: "A workshop on Weight-Space Symmetries: from Foundations to Practical Applications held in conjunction with the International Conference on Machine Learning (ICML) 2026 in Seoul, South Korea."

timezone: Asia/Seoul

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  # Schedule: "/schedule"
  Speakers: "/speakers"
  Organizers: "/organizers"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

remote_theme: pages-themes/cayman@v0.2.0
theme: jekyll-theme-cayman

plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme
  - github-pages

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
